In [72]:
import numpy as np
from numpy.linalg import norm
from collections import Counter

In [4]:
data = open('../inputs/input-day19').read().splitlines()

In [5]:
data = """--- scanner 0 ---
404,-588,-901
528,-643,409
-838,591,734
390,-675,-793
-537,-823,-458
-485,-357,347
-345,-311,381
-661,-816,-575
-876,649,763
-618,-824,-621
553,345,-567
474,580,667
-447,-329,318
-584,868,-557
544,-627,-890
564,392,-477
455,729,728
-892,524,684
-689,845,-530
423,-701,434
7,-33,-71
630,319,-379
443,580,662
-789,900,-551
459,-707,401

--- scanner 1 ---
686,422,578
605,423,415
515,917,-361
-336,658,858
95,138,22
-476,619,847
-340,-569,-846
567,-361,727
-460,603,-452
669,-402,600
729,430,532
-500,-761,534
-322,571,750
-466,-666,-811
-429,-592,574
-355,545,-477
703,-491,-529
-328,-685,520
413,935,-424
-391,539,-444
586,-435,557
-364,-763,-893
807,-499,-711
755,-354,-619
553,889,-390

""".splitlines()

In [6]:
arr, tmp = [], []
for l in data:
    if "scanner" in l:
        continue
    elif l == '':
        tmp.sort()
        arr.append(np.array(tmp))
        tmp = []
    else:
        tmp.append(np.safe_eval(l))

In [7]:
def orientation(array):
    for x in [1,-1]:
        for y in [1,-1]:
            for z in [1,-1]:
                for perm in [[0,1,2],[1,2,0],[2,0,1]]:
                    yield array[:, perm] * [x,y,z]

In [9]:
def island_props(v):
    # Get one-off shifted slices and then compare element-wise, to give
    # us a mask of start and start positions for each island.
    # Also, get the corresponding indices.
    mask = np.concatenate(( [True], v[1:] != v[:-1], [True] ))
    loc0 = np.flatnonzero(mask)

    # Get the start locations
    loc = loc0[:-1]

    # The values would be input array indexe by the start locations.
    # The lengths woul be the differentiation between start and stop indices.
    return v[loc], loc, np.diff(loc0)

In [18]:
arr[0].shape

(25, 3)

In [ ]:
arr[0].repeat_interleave(arr[0].size()[0], dim=0) - arr[1].repeat(arr[0].size()[0])

In [58]:
a = np.einsum('ij,lm->il', arr[0], np.ones(arr[1].shape)) + np.einsum('ij,lm->il', np.ones(arr[0].shape), arr[1])

In [74]:
Counter(a.flatten()).most_common()

[(-3555.0, 3),
 (4038.0, 3),
 (21.0, 2),
 (-393.0, 2),
 (4104.0, 2),
 (294.0, 2),
 (4407.0, 2),
 (4209.0, 2),
 (-720.0, 2),
 (4233.0, 2),
 (510.0, 2),
 (1650.0, 2),
 (1677.0, 2),
 (1479.0, 2),
 (-1776.0, 2),
 (-7635.0, 2),
 (-3000.0, 2),
 (-1131.0, 2),
 (-2298.0, 2),
 (1782.0, 2),
 (-1770.0, 2),
 (-2028.0, 2),
 (-2853.0, 2),
 (1839.0, 2),
 (3684.0, 2),
 (-1713.0, 2),
 (-483.0, 2),
 (-42.0, 2),
 (-459.0, 2),
 (3681.0, 2),
 (4236.0, 2),
 (4509.0, 2),
 (228.0, 2),
 (783.0, 2),
 (-1233.0, 1),
 (3918.0, 1),
 (-4881.0, 1),
 (60.0, 1),
 (-5112.0, 1),
 (87.0, 1),
 (-4317.0, 1),
 (4488.0, 1),
 (-531.0, 1),
 (3945.0, 1),
 (1713.0, 1),
 (3720.0, 1),
 (4161.0, 1),
 (3747.0, 1),
 (3072.0, 1),
 (5277.0, 1),
 (3549.0, 1),
 (6006.0, 1),
 (-3.0, 1),
 (6021.0, 1),
 (-261.0, 1),
 (-573.0, 1),
 (4578.0, 1),
 (-4221.0, 1),
 (681.0, 1),
 (267.0, 1),
 (720.0, 1),
 (-4452.0, 1),
 (747.0, 1),
 (-3657.0, 1),
 (5148.0, 1),
 (129.0, 1),
 (4605.0, 1),
 (2373.0, 1),
 (4380.0, 1),
 (4821.0, 1),
 (4764.0, 1),
 (3732.

In [ ]:
np.einsum('ij,lm',arr[0],arr[1])

In [ ]:
for l in arr[0]:
    print(arr[1] + l)

In [55]:
ans = set()
for j in orientation(arr[1]):
    print(np.einsum('ij,lm->il', arr[0], np.ones(j.shape)) + np.einsum('ij,lm->il', np.ones(arr[0].shape), j))
    # for _line in arr[0]:
    #     _j = j - _line
    #     print(_j)

[[-1.2330e+03  3.9180e+03 -4.8810e+03  2.1000e+01 -3.9300e+02  6.0000e+01
  -5.1120e+03  8.7000e+01 -4.3170e+03  4.4880e+03 -5.3100e+02  3.9450e+03
   1.7130e+03  3.7200e+03  4.1610e+03  4.1040e+03  3.7470e+03  3.0720e+03
   5.2770e+03  3.5490e+03  6.0060e+03 -3.0000e+00  6.0210e+03  2.9400e+02
  -2.6100e+02]
 [-5.7300e+02  4.5780e+03 -4.2210e+03  6.8100e+02  2.6700e+02  7.2000e+02
  -4.4520e+03  7.4700e+02 -3.6570e+03  5.1480e+03  1.2900e+02  4.6050e+03
   2.3730e+03  4.3800e+03  4.8210e+03  4.7640e+03  4.4070e+03  3.7320e+03
   5.9370e+03  4.2090e+03  6.6660e+03  6.5700e+02  6.6810e+03  9.5400e+02
   3.9900e+02]
 [-7.2000e+02  4.4310e+03 -4.3680e+03  5.3400e+02  1.2000e+02  5.7300e+02
  -4.5990e+03  6.0000e+02 -3.8040e+03  5.0010e+03 -1.8000e+01  4.4580e+03
   2.2260e+03  4.2330e+03  4.6740e+03  4.6170e+03  4.2600e+03  3.5850e+03
   5.7900e+03  4.0620e+03  6.5190e+03  5.1000e+02  6.5340e+03  8.0700e+02
   2.5200e+02]
 [-3.5010e+03  1.6500e+03 -7.1490e+03 -2.2470e+03 -2.6610e+03 -2.20

In [131]:
ans

{(-892, 524, 684),
 (-876, 649, 763),
 (-838, 591, 734),
 (-789, 900, -551),
 (-689, 845, -530),
 (-661, -816, -575),
 (-618, -824, -621),
 (-584, 868, -557),
 (-537, -823, -458),
 (-485, -357, 347),
 (-447, -329, 318),
 (-345, -311, 381),
 (7, -33, -71),
 (390, -675, -793),
 (404, -588, -901),
 (423, -701, 434),
 (443, 580, 662),
 (455, 729, 728),
 (459, -707, 401),
 (474, 580, 667),
 (528, -643, 409),
 (544, -627, -890),
 (553, 345, -567),
 (564, 392, -477),
 (630, 319, -379)}

In [104]:
arr[0]

array([[-892,  524,  684],
       [-876,  649,  763],
       [-838,  591,  734],
       [-789,  900, -551],
       [-689,  845, -530],
       [-661, -816, -575],
       [-618, -824, -621],
       [-584,  868, -557],
       [-537, -823, -458],
       [-485, -357,  347],
       [-447, -329,  318],
       [-345, -311,  381],
       [   7,  -33,  -71],
       [ 390, -675, -793],
       [ 404, -588, -901],
       [ 423, -701,  434],
       [ 443,  580,  662],
       [ 455,  729,  728],
       [ 459, -707,  401],
       [ 474,  580,  667],
       [ 528, -643,  409],
       [ 544, -627, -890],
       [ 553,  345, -567],
       [ 564,  392, -477],
       [ 630,  319, -379]])

In [93]:
arr[0]

array([[-892,  524,  684],
       [-876,  649,  763],
       [-838,  591,  734],
       [-789,  900, -551],
       [-689,  845, -530],
       [-661, -816, -575],
       [-618, -824, -621],
       [-584,  868, -557],
       [-537, -823, -458],
       [-485, -357,  347],
       [-447, -329,  318],
       [-345, -311,  381],
       [   7,  -33,  -71],
       [ 390, -675, -793],
       [ 404, -588, -901],
       [ 423, -701,  434],
       [ 443,  580,  662],
       [ 455,  729,  728],
       [ 459, -707,  401],
       [ 474,  580,  667],
       [ 528, -643,  409],
       [ 544, -627, -890],
       [ 553,  345, -567],
       [ 564,  392, -477],
       [ 630,  319, -379]])

In [94]:
arr[1]

array([[-500, -761,  534],
       [-476,  619,  847],
       [-466, -666, -811],
       [-460,  603, -452],
       [-429, -592,  574],
       [-391,  539, -444],
       [-364, -763, -893],
       [-355,  545, -477],
       [-340, -569, -846],
       [-336,  658,  858],
       [-328, -685,  520],
       [-322,  571,  750],
       [  95,  138,   22],
       [ 413,  935, -424],
       [ 515,  917, -361],
       [ 553,  889, -390],
       [ 567, -361,  727],
       [ 586, -435,  557],
       [ 605,  423,  415],
       [ 669, -402,  600],
       [ 686,  422,  578],
       [ 703, -491, -529],
       [ 729,  430,  532],
       [ 755, -354, -619],
       [ 807, -499, -711]])

In [71]:
for second in range(1,len(arr)):
    for j in orientation(arr[second]):
        
